todoapp:
  site:
    author: hyungkishin
    description: todoApp Templates for Server-side
  data:
    init: true
  feature-toggles:
    auth: true
    onlineUsersCounter: false

server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  error:
    include-binding-errors: always
    include-message: always

logging:
  level:
    '[todoapp]': debug
    '[org.springframework.web]': debug
    web: debug
    sql: debug
