todoapp:
  site:
    author: hyungkishin
    description: todoApp Templates for Server-side
  data:
    init: true

logging:
  level:
    '[org.springframework.web]': debug
    web: debug
    sql: debug