todoapp:
  site:
    author: hyungkishin
    description: todoApp Templates for Server-side
  data:
    init: true

server:
  servlet:
    encoding:
      charset: utf-8
      force: true

logging:
  level:
    '[todoapp]': debug
    '[org.springframework.web]': debug
    web: debug
    sql: debug